name: Testing with Pytest and flake8

on:
    push:
        branches: [main]

jobs:
    testing:
        runs-on: ubuntu-latest

        steps:
            - name: Check code
              uses: actions/checkout@v3

            - name: Setup up python
              uses: actions/setup-python@v4
              with:
                    python-version: '3.10'

            - name: Installing dependencies
              run: |
               python -m pip install --upgrade pip
               pip install -r requirements.txt

            - name: Lint code with flake8
              run: flake8 . --max-line-length==88

            - name: Run tests
              run: pytest