
name: Pytest

on:
    push:
        branches: [main,master]

jobs:
    pytest:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up python
              uses: actions/set-python@v4
              with:
                python-version: '3.10'
            
            - name: Installing dependencies
              run: | 
                python -m pip install --upgrade pip
                python install -r requirements.txt

            - name: Run Tests
              run: |
                pytest